"""
Django settings for AppHubCentral project.

Generated by 'django-admin startproject' using Django 3.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=bvr7-t3f-zx#3qopz+p)9sr2t(f545dp5yzet!pooiybfx2*0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "mail.electricemus.com"
EMAIL_PORT = 465
EMAIL_HOST_USER = "muzamil@electricemus.com"
EMAIL_HOST_PASSWORD = "Pakistan@112233"
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = 'muzamil@electricemus.com'
PASSWORD_RESET_TIMEOUT = 3000
